### ISSUE TITLE
Client does not support authentication protocol requested by server; consider upgrading MySQL client

### ISSUE THREAD

**Issue by yutao-huang** [siddpuri/coderogue#5]
I was trying to launch the web server on my local box, but I got the error below. The issue went away after I upgraded the `mysql` npm module to `mysql2`.

```
node:internal/process/esm_loader:42
      internalBinding('errors').triggerUncaughtException(
                                ^

Error: ER_NOT_SUPPORTED_AUTH_MODE: Client does not support authentication protocol requested by server; consider upgrading MySQL client
    at Sequence._packetToError (/home/yutao/git/coderogue/node_modules/mysql/lib/protocol/sequences/Sequence.js:47:14)
    at Handshake.ErrorPacket (/home/yutao/git/coderogue/node_modules/mysql/lib/protocol/sequences/Handshake.js:123:18)
    at Protocol._parsePacket (/home/yutao/git/coderogue/node_modules/mysql/lib/protocol/Protocol.js:291:23)
    at Parser._parsePacket (/home/yutao/git/coderogue/node_modules/mysql/lib/protocol/Parser.js:433:10)
    at Parser.write (/home/yutao/git/coderogue/node_modules/mysql/lib/protocol/Parser.js:43:10)
    at Protocol.write (/home/yutao/git/coderogue/node_modules/mysql/lib/protocol/Protocol.js:38:16)
    at Socket.<anonymous> (/home/yutao/git/coderogue/node_modules/mysql/lib/Connection.js:88:28)
    at Socket.<anonymous> (/home/yutao/git/coderogue/node_modules/mysql/lib/Connection.js:526:10)
    at Socket.emit (node:events:511:28)
    at addChunk (node:internal/streams/readable:332:12)
    --------------------
    at Protocol._enqueue (/home/yutao/git/coderogue/node_modules/mysql/lib/protocol/Protocol.js:144:48)
    at Protocol.handshake (/home/yutao/git/coderogue/node_modules/mysql/lib/protocol/Protocol.js:51:23)
    at Connection.connect (/home/yutao/git/coderogue/node_modules/mysql/lib/Connection.js:116:18)
    at Connection._implyConnect (/home/yutao/git/coderogue/node_modules/mysql/lib/Connection.js:454:10)
    at Connection.query (/home/yutao/git/coderogue/node_modules/mysql/lib/Connection.js:196:8)
    at node:internal/util:410:7
    at new Promise (<anonymous>)
    at Connection.query (node:internal/util:396:12)
    at DB.start (file:///home/yutao/git/coderogue/db/db.js:18:20)
    at Server.start (file:///home/yutao/git/coderogue/server/server.js:18:23) {
  code: 'ER_NOT_SUPPORTED_AUTH_MODE',
  errno: 1251,
  sqlMessage: 'Client does not support authentication protocol requested by server; consider upgrading MySQL client',
  sqlState: '08004',
  fatal: true
}
```

**Comment by siddpuri** [comment]
Fixed in b57046fcbb8d16e2beb5744ca0698abd32510a10
